// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int iterations = Integer.parseInt(args[0]);

        int countL = 0, countGE = 0;
        for (int iteration = 0; iteration < iterations; iteration++) {
            double r = Math.random();

            if (r < 0.5) {
                countL++;
                continue;
            }
            countGE++;
        }

        System.out.printf("> 0.5: %d times\n<= 0.5: %d times%n", countL, countGE);
        if (countGE == 0 || countL == 0) {
            return;
        }

        double ratio = (double) countL / countGE;
        System.out.println("Ratio: " + ratio);
	}
}
